In [1]:
%load_ext autoreload
%autoreload 2

In [3]:
import pandas as pd

# Metrics

In [10]:
df_meterics = pd.read_csv('out/verification_stats_agg/100-trials_conf-geq-70sample-from-val/metrics.csv')
df_meterics.head()

,total_accuracy.mean,total_accuracy.std,acc_per_class.Not_Water.mean,acc_per_class.Not_Water.std,acc_per_class.Open_Surface_Water.mean,acc_per_class.Open_Surface_Water.std,acc_per_class.Partial_Surface_Water.mean,acc_per_class.Partial_Surface_Water.std,confusion_matrix.Not_Water_OPERA_DSWx.Not_Water_OPERA_Validation.mean,confusion_matrix.Not_Water_OPERA_DSWx.Not_Water_OPERA_Validation.std,...,f1_per_class.Partial_Surface_Water.mean,f1_per_class.Partial_Surface_Water.std,supp_per_class.Not_Water.mean,supp_per_class.Not_Water.std,supp_per_class.Open_Surface_Water.mean,supp_per_class.Open_Surface_Water.std,supp_per_class.Partial_Surface_Water.mean,supp_per_class.Partial_Surface_Water.std,dswx_id,planet_id
0,0.716307,1.008495e-02,0.742874,1.115985e-02,0.970858,0.006190,0.718882,1.008521e-02,166.17,0.766139,...,0.292462,0.039780,294.16,5.807901,174.54,3.731980,32.30,4.762013,OPERA_L3_DSWx_HLS_T19UDA_20210902T154911Z_2022...,20210903_152641_60_105c
1,0.937173,1.115816e-16,0.984293,2.231632e-16,0.952880,0.000000,0.937173,1.115816e-16,167.00,0.000000,...,0.600000,0.000000,170.00,0.000000,12.00,0.000000,9.00,0.000000,OPERA_L3_DSWx_HLS_T50TMM_20210930T025915Z_2022...,20210930_021156_60_2434
2,1.000000,0.000000e+00,1.000000,0.000000e+00,1.000000,0.000000,1.000000,0.000000e+00,500.00,0.000000,...,0.000000,0.000000,500.00,0.000000,0.00,0.000000,0.00,0.000000,OPERA_L3_DSWx_HLS_T32PQA_20210911T094031Z_2022...,20210912_094213_84_240f
3,0.888083,1.009908e-02,0.941000,7.687467e-03,0.947083,0.007495,0.888083,1.009908e-02,167.00,0.000000,...,0.866298,0.013697,188.24,2.767488,37.05,2.698204,134.71,3.635668,OPERA_L3_DSWx_HLS_T20LKN_20211010T143729Z_2022...,20211010_135831_84_227e
4,0.988142,3.347448e-16,0.988142,3.347448e-16,1.000000,0.000000,0.988142,3.347448e-16,250.00,0.000000,...,0.000000,0.000000,253.00,0.000000,0.00,0.000000,0.00,0.000000,OPERA_L3_DSWx_HLS_T54JTM_20210908T003848Z_2022...,20210909_000649_94_222b

In [11]:
df_meterics.columns

Index(['total_accuracy.mean', 'total_accuracy.std',
       'acc_per_class.Not_Water.mean', 'acc_per_class.Not_Water.std',
       'acc_per_class.Open_Surface_Water.mean',
       'acc_per_class.Open_Surface_Water.std',
       'acc_per_class.Partial_Surface_Water.mean',
       'acc_per_class.Partial_Surface_Water.std',
       'confusion_matrix.Not_Water_OPERA_DSWx.Not_Water_OPERA_Validation.mean',
       'confusion_matrix.Not_Water_OPERA_DSWx.Not_Water_OPERA_Validation.std',
       'confusion_matrix.Not_Water_OPERA_DSWx.Open_Surface_Water_OPERA_Validation.mean',
       'confusion_matrix.Not_Water_OPERA_DSWx.Open_Surface_Water_OPERA_Validation.std',
       'confusion_matrix.Not_Water_OPERA_DSWx.Partial_Surface_Water_OPERA_Validation.mean',
       'confusion_matrix.Not_Water_OPERA_DSWx.Partial_Surface_Water_OPERA_Validation.std',
       'confusion_matrix.Open_Surface_Water_OPERA_DSWx.Not_Water_OPERA_Validation.mean',
       'confusion_matrix.Open_Surface_Water_OPERA_DSWx.Not_Water_OPERA_Validation.std',
       'confusion_matrix.Open_Surface_Water_OPERA_DSWx.Open_Surface_Water_OPERA_Validation.mean',
       'confusion_matrix.Open_Surface_Water_OPERA_DSWx.Open_Surface_Water_OPERA_Validation.std',
       'confusion_matrix.Open_Surface_Water_OPERA_DSWx.Partial_Surface_Water_OPERA_Validation.mean',
       'confusion_matrix.Open_Surface_Water_OPERA_DSWx.Partial_Surface_Water_OPERA_Validation.std',
       'confusion_matrix.Partial_Surface_Water_OPERA_DSWx.Not_Water_OPERA_Validation.mean',
       'confusion_matrix.Partial_Surface_Water_OPERA_DSWx.Not_Water_OPERA_Validation.std',
       'confusion_matrix.Partial_Surface_Water_OPERA_DSWx.Open_Surface_Water_OPERA_Validation.mean',
       'confusion_matrix.Partial_Surface_Water_OPERA_DSWx.Open_Surface_Water_OPERA_Validation.std',
       'confusion_matrix.Partial_Surface_Water_OPERA_DSWx.Partial_Surface_Water_OPERA_Validation.mean',
       'confusion_matrix.Partial_Surface_Water_OPERA_DSWx.Partial_Surface_Water_OPERA_Validation.std',
       'precision.Not_Water.mean', 'precision.Not_Water.std',
       'precision.Open_Surface_Water.mean', 'precision.Open_Surface_Water.std',
       'precision.Partial_Surface_Water.mean',
       'precision.Partial_Surface_Water.std', 'recall.Not_Water.mean',
       'recall.Not_Water.std', 'recall.Open_Surface_Water.mean',
       'recall.Open_Surface_Water.std', 'recall.Partial_Surface_Water.mean',
       'recall.Partial_Surface_Water.std', 'f1_per_class.Not_Water.mean',
       'f1_per_class.Not_Water.std', 'f1_per_class.Open_Surface_Water.mean',
       'f1_per_class.Open_Surface_Water.std',
       'f1_per_class.Partial_Surface_Water.mean',
       'f1_per_class.Partial_Surface_Water.std',
       'supp_per_class.Not_Water.mean', 'supp_per_class.Not_Water.std',
       'supp_per_class.Open_Surface_Water.mean',
       'supp_per_class.Open_Surface_Water.std',
       'supp_per_class.Partial_Surface_Water.mean',
       'supp_per_class.Partial_Surface_Water.std', 'dswx_id', 'planet_id'],
      dtype='object')

In [16]:
COLUMNS = ['total_accuracy.mean',
           'acc_per_class.Open_Surface_Water.mean',
           'acc_per_class.Partial_Surface_Water.mean',
#            'precision.Open_Surface_Water.mean',
#            'precision.Partial_Surface_Water.mean',
#            'recall.Open_Surface_Water.mean',
#            'recall.Partial_Surface_Water.mean'
          ]

In [17]:
COLUMN_RENAME = {'total_accuracy.mean': 'Total Accuracy (All)',
                 'precision.Open_Surface_Water.mean': 'Precision (OSW)',
                 'acc_per_class.Open_Surface_Water.mean': 'Binary Accuracy (OSW)',
                 'acc_per_class.Partial_Surface_Water.mean': 'Binary Accuracy (PSW)',
                 'precision.Partial_Surface_Water.mean': 'Precision (PSW)',
                 'recall.Open_Surface_Water.mean': 'Recall (OSW)',
                 'recall.Partial_Surface_Water.mean': 'Recall (PSW)'}
#assert set(COLUMN_RENAME.keys()) == set(COLUMNS)

In [18]:
df_temp = df_meterics[COLUMNS].agg(['mean', 'median', 'std']).round(2).astype(str)

df_temp.rename(columns=COLUMN_RENAME, inplace=True)
df_f = df_temp.T
df_f = df_f.reset_index(drop=False)
df_f = df_f.rename(columns={'index': 'Metric'})
df_f['Class'] = df_f.Metric.map(lambda m: m[-4:-1])
df_f['Metric'] = df_f.Metric.map(lambda m: m[:-6])
df_f.sort_values(by=['Class', 'Metric'], inplace=True)
df_f = df_f.set_index(['Class', 'Metric'])
df_f.rename(columns={'mean': '$\mu$', 'std': '$\sigma$', 'median': '$\eta$'}, inplace=True)
df_f

                      $\mu$ $\eta$ $\sigma$
Class Metric
All   Total Accuracy   0.83   0.85     0.17
OSW   Binary Accuracy   0.9   0.98     0.12
PSW   Binary Accuracy  0.84   0.85     0.15

In [19]:
print(df_f.style.to_latex(multirow_align='t', hrules=True))

\begin{tabular}{lllll}
\toprule
 &  & $\mu$ & $\eta$ & $\sigma$ \\
Class & Metric &  &  &  \\
\midrule
All & Total Accuracy & 0.83 & 0.85 & 0.17 \\
OSW & Binary Accuracy & 0.9 & 0.98 & 0.12 \\
PSW & Binary Accuracy & 0.84 & 0.85 & 0.15 \\
\bottomrule
\end{tabular}